### ISSUE TITLE
Call kills app

### ISSUE THREAD

**Issue by seanmiller802** [tiaanduplessis/react-native-phone-call#14]
Attempting to make a call from my app kills the app on iOS 12

**Comment by NeelamSoni129** [comment]
this is happening for me too.

**Comment by SashaStojanovic** [comment]
Still happening here. Any idea on a fix?

**Comment by TheBurgerShot** [comment]
> Still happening here. Any idea on a fix?

@NeelamSoni129 @SashaStojanovic 

Alternatively you could try 

```
import {Linking} from 'react-native'

Linking.openURL(`tel:${phoneNumber}`)
```

**Comment by tiaanduplessis** [comment]
This issue is stale at this point so I'm closing it for now. Please reopen if it persists. 

Also, confirm that you are catching the promise rejection as a check is performed with [canOpenUrl](https://reactnative.dev/docs/linking#canopenurl).

You can try adding the following to the `Info.plist`:

```
<key>LSApplicationQueriesSchemes</key> 
<array> 
  <string>tel</string> 
  <string>telprompt</string> 
</array>
```
