### ISSUE TITLE
phone call intent with extension does not work

### ISSUE THREAD

**Issue by RadomirKus** [tiaanduplessis/react-native-phone-call#15]
Calling 'call' method with number '9093900003,,,3,,,274' as provided in readme does not open intent with pauses and extension - those are simply stripped. I am not sure whether RN Linking actually supports uris with extensions.
Do you have any idea how to implement such behaviour or how to make you example working?

**Comment by tiaanduplessis** [comment]
Marking as stale. This feature was added here -> https://github.com/tiaanduplessis/react-native-phone-call/commit/c62e4aff44545c4efea86cf78840ccf88d076c1f

Unfortunately, I haven't used it myself so I'm not able to assist at this stage.
