### ISSUE TITLE
Cannot add # in the phone number

### ISSUE THREAD

**Issue by BuddhiWeerasinghe** [tiaanduplessis/react-native-phone-call#16]
While the number including #, the content after # is not visible in the dial pad.

const args = {
number: "*#123",
prompt: true
};

This show only * in the dial pad.

**Comment by BuddhiWeerasinghe** [comment]
While the number including #, the content after # is not visible in the dial pad. 

const args = {
      number: "*#123", 
      prompt: true 
};

This show only * in the dial pad.

**Comment by OussemaBAT** [comment]
Put the whole phone number like this :  

const args = {
number:  encodeURIComponent("*#123"),
prompt: true
};

Hope this helped

**Comment by OussemaBA** [comment]
Put the whole phone number like this :

const args = {
number: encodeURIComponent("*#123"),
prompt: true
};

Hope this helps

**Comment by tiaanduplessis** [comment]
Closing for now. Please reopen if the possible solution suggested by @OussemaBA does not work.
