### ISSUE TITLE
Invalid URL in IOS

### ISSUE THREAD

**Issue by sauravkumar-tudip** [tiaanduplessis/react-native-phone-call#2]
Hi, I am getting invalid URL message for IOS.

**Comment by danijel** [comment]
for me calling works but if I do cancel on prompt then I get invalid telprompt url
catching error however avoids error message
```
  async onCall() {
    const args = {
      number: this.props.phone
      prompt: true
    };

    try {
      await call(args);
    } catch (e) {
      //hande error
    }
  }
```

**Comment by tiaanduplessis** [comment]
@sauravkumar-tudip could you please provide a example number that causes the issue

**Comment by sauravkumar-tudip** [comment]
Hey, @tiaanduplessis thanks for your reply and I have solved the issue.

**Comment by tiaanduplessis** [comment]
@sauravkumar-tudip glad you got it resolved 😄

**Comment by bnerDY** [comment]
Hi @tiaanduplessis ,
Is it possible to call a number like 86-021-63216888?
Could you please provide valid phone string format.
Thanks in advance.

**Comment by tiaanduplessis** [comment]
Hi @bnerDY , Any valid number should be supported. For 86-021-63216888 you would need to remove the hyphens, so 8602163216888 should work

**Comment by Veronica1026** [comment]
Hey I am getting the same error, and is there a way to fix it?
my code is

callTU = () => {
  const callnumber = {
    number: "9093900003", // String value with the number to call
    prompt: false // Optional boolean property. Determines if the user should be prompt prior to the call
  };
  call(callnumber).catch(console.error);
};

and I am calling it is this component

 <ActionButton onPress={this.callTU} title="Call" />

when I hit the button, I get the error saying "the URL is invalid: tel:9093900003"
even if I change the phone number into my own number, the problem is still there...

**Comment by Veronica1026** [comment]
oh, I see, it has nothing with the code itself, it is just that the simulator has no phone-call functions, when I test my code in a real device, it works out fine, thanks a lot!

**Comment by tiaanduplessis** [comment]
@Veronica1026 glad you got it resolved 😄

**Comment by Rahuldiff** [comment]
Hi, I m getting error Invalid URL: tel: 'myNumber' in IOS. Can u please help me in fixing up? In Android it works pretty well.

**Comment by Veronica1026** [comment]
Are you using Xcode simulator or a real iOS phone? I got the same error when using simulator, but after I build the app to my iPhone, it works out fine.
Xcode simulator just does nor support phone call feature

**Comment by zeropaper** [comment]
I got the same error (because I was trying in the simulator)...
maybe it could be worth mentioning that it only works on a phone in the README.md.

**Comment by tiaanduplessis** [comment]
@zeropaper good idea. I'll add a note on the README
