### ISSUE TITLE
11 vulnerabilities must be fixed manually

### ISSUE THREAD

**Issue by raphaelalvarenga** [tiaanduplessis/react-native-phone-call#20]
Hello,

I npm installed react-native-phone-call and the package manager alerted that there were 1666 high vulnerabilities and 11 low vulnerabilities to be fixed. I inserted "npm audit fix" and it fixed the high ones.

Now, it says: "11 vulnerabilities required manual review and could not be updated".

I'm using Expo. The report is:

  Low             Regular Expression Denial of Service                          
                                                                                
  Package         braces                                                        
                                                                                
  Patched in      >=2.3.1                                                       
                                                                                
  Dependency of   261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                                                                                
  Path            261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                  > @react-native-community/cli > metro > jest-haste-map >      
                  micromatch > braces                                           
                                                                                
  More info       https://npmjs.com/advisories/786                              
                                                                                
                                                                                
  Low             Regular Expression Denial of Service                          
                                                                                
  Package         braces                                                        
                                                                                
  Patched in      >=2.3.1                                                       
                                                                                
  Dependency of   261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                                                                                
  Path            261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                  > @react-native-community/cli > metro-config > metro >        
                  jest-haste-map > micromatch > braces                          
                                                                                
  More info       https://npmjs.com/advisories/786                              
                                                                                
                                                                                
  Low             Regular Expression Denial of Service                          
                                                                                
  Package         braces                                                        
                                                                                
  Patched in      >=2.3.1                                                       
                                                                                
  Dependency of   261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                                                                                
  Path            261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                  > @react-native-community/cli > metro > metro-cache >         
                  metro-core > jest-haste-map > micromatch > braces             
                                                                                
  More info       https://npmjs.com/advisories/786                              
                                                                                
                                                                                
  Low             Regular Expression Denial of Service                          
                                                                                
  Package         braces                                                        
                                                                                
  Patched in      >=2.3.1                                                       
                                                                                
  Dependency of   261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                                                                                
  Path            261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                  > @react-native-community/cli > metro-config > metro >        
                  metro-cache > metro-core > jest-haste-map > micromatch >      
                  braces                                                        
                                                                                
  More info       https://npmjs.com/advisories/786                              
                                                                                
                                                                                
  Low             Regular Expression Denial of Service                          
                                                                                
  Package         braces                                                        
                                                                                
  Patched in      >=2.3.1                                                       
                                                                                
  Dependency of   261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                                                                                
  Path            261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                  > @react-native-community/cli > metro > metro-config >        
                  metro-cache > metro-core > jest-haste-map > micromatch >      
                  braces                                                        
                                                                                
  More info       https://npmjs.com/advisories/786                              
                                                                                
                                                                                
  Low             Regular Expression Denial of Service                          
                                                                                
  Package         braces                                                        
                                                                                
  Patched in      >=2.3.1                                                       
                                                                                
  Dependency of   261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                                                                                
  Path            261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                  > @react-native-community/cli > metro-config > metro-cache >  
                  metro-core > jest-haste-map > micromatch > braces             
                                                                                
  More info       https://npmjs.com/advisories/786                              
                                                                                
                                                                                
  Low             Regular Expression Denial of Service                          
                                                                                
  Package         braces                                                        
                                                                                
  Patched in      >=2.3.1                                                       
                                                                                
  Dependency of   261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                                                                                
  Path            261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                  > @react-native-community/cli > metro > metro-config >        
                  metro-core > jest-haste-map > micromatch > braces             
                                                                                
  More info       https://npmjs.com/advisories/786                              
                                                                                
                                                                                
  Low             Regular Expression Denial of Service                          
                                                                                
  Package         braces                                                        
                                                                                
  Patched in      >=2.3.1                                                       
                                                                                
  Dependency of   261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                                                                                
  Path            261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                  > @react-native-community/cli > metro-config > metro-core >   
                  jest-haste-map > micromatch > braces                          
                                                                                
  More info       https://npmjs.com/advisories/786                              
                                                                                
                                                                                
  Low             Regular Expression Denial of Service                          
                                                                                
  Package         braces                                                        
                                                                                
  Patched in      >=2.3.1                                                       
                                                                                
  Dependency of   261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                                                                                
  Path            261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                  > @react-native-community/cli > metro > metro-core >          
                  jest-haste-map > micromatch > braces                          
                                                                                
  More info       https://npmjs.com/advisories/786                              
                                                                                
                                                                                
  Low             Regular Expression Denial of Service                          
                                                                                
  Package         braces                                                        
                                                                                
  Patched in      >=2.3.1                                                       
                                                                                
  Dependency of   261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                                                                                
  Path            261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                  > @react-native-community/cli > metro-config > metro >        
                  metro-core > jest-haste-map > micromatch > braces             
                                                                                
  More info       https://npmjs.com/advisories/786                              
                                                                                
                                                                                
  Low             Regular Expression Denial of Service                          
                                                                                
  Package         braces                                                        
                                                                                
  Patched in      >=2.3.1                                                       
                                                                                
  Dependency of   261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                                                                                
  Path            261a5a0f90cf47bb4651d059c9a4782169305e0aad1a8cefc3ed9370dc0…  
                  > @react-native-community/cli > metro-core > jest-haste-map   
                  > micromatch > braces                                         
                                                                                
  More info       https://npmjs.com/advisories/786                              
                                                                                
found 11 low severity vulnerabilities in 37960 scanned packages
  11 vulnerabilities require manual review. See the full report for details.

**Comment by raphaelalvarenga** [comment]
Anyone?

**Comment by tiaanduplessis** [comment]
This package does not have any dependencies except [standard](https://standardjs.com/) which is a dev dependency and on the latest version as of v1.1.0
