### ISSUE TITLE
can't call Bangla phone number for android 9

### ISSUE THREAD

**Issue by rezaulk** [tiaanduplessis/react-native-phone-call#23]
I can't call Bangla phone number for android 9 but up to android 8 working well.
 Still, SMS send in Bangla number. What can I do to fix this problem?

![Capture](https://user-images.githubusercontent.com/33289815/68831138-d0db7500-06d7-11ea-8d8b-df72f64b3468.PNG)

**Comment by tiaanduplessis** [comment]
Try the number with the country code prefix. 

This issue is stale at this point, but please reopen it if it persists.
