### ISSUE TITLE
invalid URL provided: tel: xxxxxxxxxx

### ISSUE THREAD

**Issue by madsongr** [tiaanduplessis/react-native-phone-call#25]
I noticed this error can happen on iOS simulator but I'm getting it on Android even if I build the APK or on Expo. It was working fine with Expo some weeks ago but now it's not anymore. I didn't change anything. It just stopped working.

```
const phoneargs = {
    number: 'xxxxxxxxxx',
    prompt: true
}

function handleCall() {
    console.log(phoneargs.number);
    call(phoneargs).catch(console.error);
}

return(
    <View style={styles.actionItem}>
         <Button
             icon={() => (
                 <MaterialIcons
                     name="phone-in-talk"
                     size={24}
                 />
             )}
              color="#333333"
              style={styles.actionBtn}
              onPress={handleCall}
          >
              <Text style={styles.itemInfo}>Call</Text>
          </Button>
    </View>
)
``` 

I tried changing the phone number my it just doesn't work.

**Comment by nullbytesoftware** [comment]
Having the same issue on Android. But working fine on IOS

**Comment by madsongr** [comment]
> Having the same issue on Android. But working fine on IOS

I'm using 

```Linking.openURL(`tel:${phoneargs.number}`);```

instead of

`call(phoneargs).catch(console.error);`

**Comment by eduardoprentcomau** [comment]
@madsongr Looks like the Linking.canOpenURL(url) is returning false inside the openLink:

```js
const openLink = (url, cb) => {
  return Linking.canOpenURL(url).then(canOpen => {
    if (!canOpen) {
      return createError(`invalid URL provided: ${url}`)
    } else {
      return Linking.openURL(url).catch((err) => Promise.reject(err))
    }
  })
}
```

Seems to be related to this issue:
https://github.com/facebook/react-native/issues/30909

**Comment by tiaanduplessis** [comment]
Thanks @eduardoprentcomau. I've [updated the README](https://github.com/tiaanduplessis/react-native-phone-call#running-on-android-sdk-30) to mention this. 

@madsongr there is now an additional `skipCanOpen` configuration option from version v1.2.0 that can be used.
