### ISSUE TITLE
how can hide phone number when calling to that

### ISSUE THREAD

**Issue by hemedani** [tiaanduplessis/react-native-phone-call#5]
I want's to hide phone number when calling to any number for my customer because my customer are taxi driver and they can call to the passenger but i want's the taxi driver can not see the passenger phone number when calling to that, is it possible ?

**Comment by tiaanduplessis** [comment]
@hemedani sorry for the late response. This package is only a wrapper around the linking API so I don't believe it will be possible, but [react-native-immediate-phone-call](https://github.com/wumke/react-native-immediate-phone-call) may resolve your problem

**Comment by hemedani** [comment]
Tanks

**Comment by sebgam** [comment]
finally you solved it?

**Comment by PhaNToMloRDs** [comment]
react-native-immediate-phone-call dose'nt work for me!
i got this error : 
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
can you help me and write example?

**Comment by Luisquii** [comment]
did you solve it?
