### ISSUE TITLE
Attempt to invoke virtual method `boolean java.lang.string.endsWith(java.lang.string)` on a null object reference

### ISSUE THREAD

**Issue by vijay-vadlamani** [tiaanduplessis/react-native-phone-call#8]
I am getting the above stated error in android devices but works perfectly fine in IOS.

**Comment by tiaanduplessis** [comment]
@vijay-vadlamani I think it is related to: https://github.com/expo/expo/issues/1733

**Comment by vijay-vadlamani** [comment]
Thank you

**Comment by tiaanduplessis** [comment]
@vijay-vadlamani glad to help.
